name: "CI: JhonMotion3D Continuous Integrating"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Runs installation
        run: npm install
      - name: Run linter
        run: npm run lint
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
      - name: Runs installation
        run: npm install
      - name: Runs test
        run: npm run test
